// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace POC
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class UIMap
    {
        
        #region Properties
        public UITaxforWoodburyAshbyNWindow UITaxforWoodburyAshbyNWindow
        {
            get
            {
                if ((this.mUITaxforWoodburyAshbyNWindow == null))
                {
                    this.mUITaxforWoodburyAshbyNWindow = new UITaxforWoodburyAshbyNWindow();
                }
                return this.mUITaxforWoodburyAshbyNWindow;
            }
        }
        #endregion
        
        #region Fields
        private UITaxforWoodburyAshbyNWindow mUITaxforWoodburyAshbyNWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UITaxforWoodburyAshbyNWindow : BrowserWindow
    {
        
        public UITaxforWoodburyAshbyNWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Tax for: Woodbury-Ashby/NeuTestTradePartnerS dba NeuTradePartnerBusinessName";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Tax for: Woodbury-Ashby/NeuTestTradePartnerS dba NeuTradePartnerBusinessName");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UITaxforWoodburyAshbyNDocument UITaxforWoodburyAshbyNDocument
        {
            get
            {
                if ((this.mUITaxforWoodburyAshbyNDocument == null))
                {
                    this.mUITaxforWoodburyAshbyNDocument = new UITaxforWoodburyAshbyNDocument(this);
                }
                return this.mUITaxforWoodburyAshbyNDocument;
            }
        }
        #endregion
        
        #region Fields
        private UITaxforWoodburyAshbyNDocument mUITaxforWoodburyAshbyNDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UITaxforWoodburyAshbyNDocument : HtmlDocument
    {
        
        public UITaxforWoodburyAshbyNDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Tax for: Woodbury-Ashby/NeuTestTradePartnerS dba NeuTradePartnerBusinessName";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Tax/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://purchasepro.qa.pulte.com/Tax/#5-905-954";
            this.WindowTitles.Add("Tax for: Woodbury-Ashby/NeuTestTradePartnerS dba NeuTradePartnerBusinessName");
            #endregion
        }
        
        #region Properties
        public UITax_contentPane UITax_contentPane
        {
            get
            {
                if ((this.mUITax_contentPane == null))
                {
                    this.mUITax_contentPane = new UITax_contentPane(this);
                }
                return this.mUITax_contentPane;
            }
        }
        #endregion
        
        #region Fields
        private UITax_contentPane mUITax_contentPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UITax_contentPane : HtmlDiv
    {
        
        public UITax_contentPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "tax_content";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Contracting Tax % % Trade Categories\r\n\r\n";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"tax_content\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "10";
            this.WindowTitles.Add("Tax for: Woodbury-Ashby/NeuTestTradePartnerS dba NeuTradePartnerBusinessName");
            #endregion
        }
        
        #region Properties
        public HtmlEdit TradePartnerNameEdit
        {
            get
            {
                if ((this.mTradePartnerNameEdit == null))
                {
                    this.mTradePartnerNameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mTradePartnerNameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mTradePartnerNameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = null;
                    this.mTradePartnerNameEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mTradePartnerNameEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mTradePartnerNameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mTradePartnerNameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mTradePartnerNameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "style=\"width: 197px;\" type=\"text\" autoco";
                    this.mTradePartnerNameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mTradePartnerNameEdit.WindowTitles.Add("Tax for: Woodbury-Ashby/NeuTestTradePartnerS dba NeuTradePartnerBusinessName");
                    #endregion
                }
                return this.mTradePartnerNameEdit;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mTradePartnerNameEdit;
        #endregion
    }
}
